name: ExtraCommands
main: ChampOfGames\ExtraCommands\Main
version: 1.0.0
api: 4.0.0
author: ChampOfGamesYT
commands:
  fly:
    description: Set yourelf into the flymode
  heal:
    description: §d§lHeals you
  feed:
    description: §a§lFull hunger
  food:
    description: §l§aGives you food
  gmc:
    description: Set gamemode to creative mode
  gms:
    description: Set gamemode to survival mode
  gma:
    description: Set gamemode to adventure mode  
